(:BEGIN-ARRAY
 :STRING-DELIMITER "JSON Test Pattern pass1" :STRING-DELIMITER
 :VALUE-SEPARATOR
 :BEGIN-OBJECT
 :STRING-DELIMITER "object with 1 member" :STRING-DELIMITER :NAME-SEPARATOR
 :BEGIN-ARRAY
 :STRING-DELIMITER "array with 1 element" :STRING-DELIMITER
 :END-ARRAY
 :END-OBJECT
 :VALUE-SEPARATOR
 :BEGIN-OBJECT
 :END-OBJECT
 :VALUE-SEPARATOR
 :BEGIN-ARRAY
 :END-ARRAY
 :VALUE-SEPARATOR
 -42
 :VALUE-SEPARATOR
 :TRUE
 :VALUE-SEPARATOR
 :FALSE
 :VALUE-SEPARATOR
 :NULL
 :VALUE-SEPARATOR
 :BEGIN-OBJECT
 :STRING-DELIMITER "integer" :STRING-DELIMITER :NAME-SEPARATOR 1234567890 :VALUE-SEPARATOR
 :STRING-DELIMITER "real" :STRING-DELIMITER :NAME-SEPARATOR -987654321/100000 :VALUE-SEPARATOR
 :STRING-DELIMITER "e" :STRING-DELIMITER :NAME-SEPARATOR  123456789/1000000000000000000000 :VALUE-SEPARATOR
 :STRING-DELIMITER "E" :STRING-DELIMITER :NAME-SEPARATOR 12345678900000000000000000000000000 :VALUE-SEPARATOR
 :STRING-DELIMITER :STRING-DELIMITER :NAME-SEPARATOR 23456789012000000000000000000000000000000000000000000000000000000000000000000 :VALUE-SEPARATOR
 :STRING-DELIMITER "zero" :STRING-DELIMITER :NAME-SEPARATOR 0 :VALUE-SEPARATOR
 :STRING-DELIMITER "one" :STRING-DELIMITER :NAME-SEPARATOR 1 :VALUE-SEPARATOR
 :STRING-DELIMITER "space" :STRING-DELIMITER :NAME-SEPARATOR :STRING-DELIMITER " " :STRING-DELIMITER :VALUE-SEPARATOR
 :STRING-DELIMITER "quote" :STRING-DELIMITER :NAME-SEPARATOR :STRING-DELIMITER #\" :STRING-DELIMITER :VALUE-SEPARATOR
 :STRING-DELIMITER "backslash" :STRING-DELIMITER :NAME-SEPARATOR :STRING-DELIMITER #\\ :STRING-DELIMITER :VALUE-SEPARATOR
 :STRING-DELIMITER "controls" :STRING-DELIMITER :NAME-SEPARATOR
 :STRING-DELIMITER #\b #\f #\n #\r #\t :STRING-DELIMITER :VALUE-SEPARATOR
 :STRING-DELIMITER "slash" :STRING-DELIMITER :NAME-SEPARATOR :STRING-DELIMITER "/ & " #\/ :STRING-DELIMITER :VALUE-SEPARATOR
 :STRING-DELIMITER "alpha" :STRING-DELIMITER :NAME-SEPARATOR :STRING-DELIMITER "abcdefghijklmnopqrstuvwyz" :STRING-DELIMITER :VALUE-SEPARATOR
 :STRING-DELIMITER "ALPHA" :STRING-DELIMITER :NAME-SEPARATOR :STRING-DELIMITER "ABCDEFGHIJKLMNOPQRSTUVWYZ" :STRING-DELIMITER :VALUE-SEPARATOR
 :STRING-DELIMITER "digit" :STRING-DELIMITER :NAME-SEPARATOR :STRING-DELIMITER "0123456789" :STRING-DELIMITER :VALUE-SEPARATOR
 :STRING-DELIMITER "0123456789" :STRING-DELIMITER :NAME-SEPARATOR :STRING-DELIMITER "digit" :STRING-DELIMITER :VALUE-SEPARATOR
 :STRING-DELIMITER "special" :STRING-DELIMITER :NAME-SEPARATOR
 :STRING-DELIMITER "`1~!@#$%^&*()_+-={':[,]}|;.</>?" :STRING-DELIMITER :VALUE-SEPARATOR
 :STRING-DELIMITER "hex" :STRING-DELIMITER :NAME-SEPARATOR
 :STRING-DELIMITER #x0123 #x4567 #x89ab #xcdef #xabcd #xef4a :STRING-DELIMITER :VALUE-SEPARATOR
 :STRING-DELIMITER "true" :STRING-DELIMITER :NAME-SEPARATOR :TRUE :VALUE-SEPARATOR
 :STRING-DELIMITER "false" :STRING-DELIMITER :NAME-SEPARATOR :FALSE :VALUE-SEPARATOR
 :STRING-DELIMITER "null" :STRING-DELIMITER :NAME-SEPARATOR :NULL :VALUE-SEPARATOR
 :STRING-DELIMITER "array" :STRING-DELIMITER :NAME-SEPARATOR :BEGIN-ARRAY :END-ARRAY :VALUE-SEPARATOR
 :STRING-DELIMITER "object" :STRING-DELIMITER :NAME-SEPARATOR :BEGIN-OBJECT :END-OBJECT :VALUE-SEPARATOR
 :STRING-DELIMITER "address" :STRING-DELIMITER :NAME-SEPARATOR :STRING-DELIMITER "50 St. James Street" :STRING-DELIMITER :VALUE-SEPARATOR
 :STRING-DELIMITER "url" :STRING-DELIMITER :NAME-SEPARATOR :STRING-DELIMITER "http://www.JSON.org/" :STRING-DELIMITER :VALUE-SEPARATOR
 :STRING-DELIMITER "comment" :STRING-DELIMITER :NAME-SEPARATOR :STRING-DELIMITER "// /* <!-- --" :STRING-DELIMITER :VALUE-SEPARATOR
 :STRING-DELIMITER "# -- --> */" :STRING-DELIMITER :NAME-SEPARATOR :STRING-DELIMITER " " :STRING-DELIMITER :VALUE-SEPARATOR
 :STRING-DELIMITER " s p a c e d " :STRING-DELIMITER :NAME-SEPARATOR
 :BEGIN-ARRAY 1 :VALUE-SEPARATOR 2 :VALUE-SEPARATOR 3
 :VALUE-SEPARATOR
 4 :VALUE-SEPARATOR 5 :VALUE-SEPARATOR 6 :VALUE-SEPARATOR 7 :END-ARRAY
 :VALUE-SEPARATOR
 :STRING-DELIMITER "compact" :STRING-DELIMITER :NAME-SEPARATOR
 :BEGIN-ARRAY
 1 :VALUE-SEPARATOR 2 :VALUE-SEPARATOR 3 :VALUE-SEPARATOR 4 :VALUE-SEPARATOR
 5 :VALUE-SEPARATOR 6 :VALUE-SEPARATOR 7
 :END-ARRAY
 :VALUE-SEPARATOR
 :STRING-DELIMITER "jsontext" :STRING-DELIMITER :NAME-SEPARATOR
 :STRING-DELIMITER "{" #\" "object with 1 member" #\" ":[" #\" "array with 1 element" #\" "]}" :STRING-DELIMITER
 :VALUE-SEPARATOR
 :STRING-DELIMITER "quotes" :STRING-DELIMITER :NAME-SEPARATOR
 :STRING-DELIMITER "&#34; " #x0022 " %22 0x22 034 &#x22;" :STRING-DELIMITER
 :VALUE-SEPARATOR
 :STRING-DELIMITER
 #\/ #\\ #\" #xCAFE #xBABE #xAB98 #xFCDE #xbcda #xef4A
 #\b #\f #\n #\r #\t
 "`1~!@#$%^&*()_+-=[]{}|;:',./<>?"
 :STRING-DELIMITER
 :NAME-SEPARATOR
 :STRING-DELIMITER
 "A key can be any string" :STRING-DELIMITER
 :END-OBJECT
 :VALUE-SEPARATOR
 1/2 :VALUE-SEPARATOR 493/5
 :VALUE-SEPARATOR
 2486/25
 :VALUE-SEPARATOR
 1066 :VALUE-SEPARATOR
 10 :VALUE-SEPARATOR
 1 :VALUE-SEPARATOR
 1/10 :VALUE-SEPARATOR
 1 :VALUE-SEPARATOR 2 :VALUE-SEPARATOR 2
 :VALUE-SEPARATOR :STRING-DELIMITER "rosebud" :STRING-DELIMITER
 :END-ARRAY
 :eof)





(:BEGIN-ARRAY
 "JSON Test Pattern pass1"
 :BEGIN-OBJECT "object with 1 member" :BEGIN-ARRAY  "array with 1 element" :END-ARRAY :END-OBJECT
 :BEGIN-OBJECT :END-OBJECT
 :BEGIN-ARRAY :END-ARRAY
 -42
 :TRUE
 :FALSE
 :NULL
 :BEGIN-OBJECT
 "integer" 1234567890
 "real" -9876.543210d0
 "e"  0.123456789d-12
 "E" 12345678900000000000000000000000000
 "" 23456789012000000000000000000000000000000000000000000000000000000000000000000
 "zero" 0
 "one" 1
 "space" " "
 "quote" "\""
 "backslash" "\\"
 "controls" "
	"
 "slash" "/ & /"
 "alpha" "abcdefghijklmnopqrstuvwyz"
 "ALPHA" "ABCDEFGHIJKLMNOPQRSTUVWYZ"
 "digit" "0123456789"
 "0123456789" "digit"
 "special" "`1~!@#$%^&*()_+-={':[,]}|;.</>?"
 "hex" "ģ䕧覫췯ꯍ"
 "true" :TRUE
 "false" :FALSE
 "null" :NULL
 "array" :BEGIN-ARRAY :END-ARRAY
 "object" :BEGIN-OBJECT :END-OBJECT
 "address" "50 St. James Street"
 "url" "http://www.JSON.org/"
 "comment" "// /* <!-- --"
 "# -- --> */" " "
 " s p a c e d " :BEGIN-ARRAY 1 2 3
 4 5 6 7 :END-ARRAY "compact"
 :BEGIN-ARRAY
 1 2 3 4 5 6 7
 :END-ARRAY
 "jsontext" "{\"object with 1 member\":[\"array with 1 element\"]}"
 "quotes" "&#34; \" %22 0x22 034 &#x22;"
 "/\\\"쫾몾ꮘﳞ볚
	`1~!@#$%^&*()_+-=[]{}|;:',./<>?"
 "A key can be any string"
 :END-OBJECT
 0.5d0 98.6d0
 99.44d0
 1066
 10
 1
 0.1d0
 1 2 2
 "rosebud" :END-ARRAY
 :eof)
